/** First 100 AI terms to learn — section id + exact term label as in sections data. */
export const AI_TERM_STARTER_100: { sectionId: string; term: string }[] = [
  { sectionId: "big-picture", term: "Artificial intelligence (AI)" },
  { sectionId: "big-picture", term: "Machine learning (ML)" },
  { sectionId: "big-picture", term: "Deep learning" },
  { sectionId: "big-picture", term: "Generative AI (GenAI)" },
  { sectionId: "big-picture", term: "Narrow AI (weak AI)" },
  { sectionId: "python-ecosystem", term: "CPython" },
  { sectionId: "python-ecosystem", term: "Virtual environments (venv)" },
  { sectionId: "python-ecosystem", term: "Jupyter notebooks" },
  { sectionId: "python-ecosystem", term: "PyTorch" },
  { sectionId: "python-ecosystem", term: "scikit-learn" },
  { sectionId: "python-ecosystem", term: "Hugging Face Transformers" },
  { sectionId: "data-terms", term: "Dataset" },
  { sectionId: "data-terms", term: "Feature" },
  { sectionId: "data-terms", term: "X matrix (inputs)" },
  { sectionId: "data-terms", term: "y vector (targets)" },
  { sectionId: "data-terms", term: "Pandas DataFrame" },
  { sectionId: "data-terms", term: "Train / validation / test split" },
  { sectionId: "data-terms", term: "Data leakage" },
  { sectionId: "ml-basics", term: "Model" },
  { sectionId: "ml-basics", term: "Loss / objective" },
  { sectionId: "ml-basics", term: "Gradient descent" },
  { sectionId: "ml-basics", term: "Overfitting" },
  { sectionId: "ml-basics", term: "Underfitting" },
  { sectionId: "ml-basics", term: "Regularization" },
  { sectionId: "ml-basics", term: "fit / predict / transform" },
  { sectionId: "ml-basics", term: "Hyperparameter" },
  { sectionId: "supervised", term: "Classification" },
  { sectionId: "supervised", term: "Regression" },
  { sectionId: "supervised", term: "Logistic regression / softmax" },
  { sectionId: "supervised", term: "Decision trees / ensembles" },
  { sectionId: "supervised", term: "Gradient boosting (XGBoost / LightGBM / CatBoost)" },
  { sectionId: "unsupervised", term: "Clustering" },
  { sectionId: "unsupervised", term: "Anomaly detection" },
  { sectionId: "training", term: "Forward pass" },
  { sectionId: "training", term: "Backward pass (backprop)" },
  { sectionId: "training", term: "Epoch" },
  { sectionId: "training", term: "Batch / minibatch" },
  { sectionId: "training", term: "Learning rate" },
  { sectionId: "training", term: "Optimizer" },
  { sectionId: "evaluation", term: "Confusion matrix" },
  { sectionId: "evaluation", term: "Accuracy" },
  { sectionId: "evaluation", term: "Precision" },
  { sectionId: "evaluation", term: "Recall" },
  { sectionId: "evaluation", term: "F1 score" },
  { sectionId: "evaluation", term: "ROC-AUC" },
  { sectionId: "evaluation", term: "Cross-validation" },
  { sectionId: "deep-learning", term: "Activation function" },
  { sectionId: "deep-learning", term: "Convolutional neural network (CNN)" },
  { sectionId: "deep-learning", term: "Dropout" },
  { sectionId: "deep-learning", term: "PyTorch tensors" },
  { sectionId: "nlp", term: "Token" },
  { sectionId: "nlp", term: "Tokenization" },
  { sectionId: "nlp", term: "Language modeling" },
  { sectionId: "llm", term: "Transformer" },
  { sectionId: "llm", term: "Self-attention" },
  { sectionId: "llm", term: "Large language model (LLM)" },
  { sectionId: "llm", term: "Context window" },
  { sectionId: "llm", term: "Pre-training vs downstream task" },
  { sectionId: "prompt-engineering", term: "Prompt" },
  { sectionId: "prompt-engineering", term: "System prompt" },
  { sectionId: "prompt-engineering", term: "Few-shot prompting" },
  { sectionId: "prompt-engineering", term: "Chain-of-thought (CoT)" },
  { sectionId: "embeddings", term: "Embedding" },
  { sectionId: "embeddings", term: "Vector database" },
  { sectionId: "embeddings", term: "Similarity scoring" },
  { sectionId: "rag", term: "RAG pipeline" },
  { sectionId: "rag", term: "Chunking strategy" },
  { sectionId: "rag", term: "Retriever" },
  { sectionId: "rag", term: "Grounding / grounding failure" },
  { sectionId: "agents", term: "AI agent" },
  { sectionId: "agents", term: "Agent loop" },
  { sectionId: "agents", term: "Tool" },
  { sectionId: "agents", term: "Tool use / tool calling" },
  { sectionId: "agents", term: "Memory" },
  { sectionId: "agents", term: "ReAct" },
  { sectionId: "agents", term: "LangChain" },
  { sectionId: "agents", term: "LangGraph" },
  { sectionId: "agents", term: "Guardrail" },
  { sectionId: "mcp", term: "Model Context Protocol (MCP)" },
  { sectionId: "mcp", term: "MCP server" },
  { sectionId: "mcp", term: "Tool schema" },
  { sectionId: "fine-tuning", term: "LoRA" },
  { sectionId: "fine-tuning", term: "Instruction tuning" },
  { sectionId: "fine-tuning", term: "Supervised fine-tuning (SFT)" },
  { sectionId: "fine-tuning", term: "DPO (direct preference optimization)" },
  { sectionId: "inference", term: "Inference" },
  { sectionId: "inference", term: "Quantization" },
  { sectionId: "inference", term: "Throughput vs latency" },
  { sectionId: "inference", term: "vLLM" },
  { sectionId: "model-types", term: "Foundation model" },
  { sectionId: "generative-ai", term: "Temperature / top-p sampling" },
  { sectionId: "safety", term: "Prompt injection" },
  { sectionId: "safety", term: "Red teaming" },
  { sectionId: "mlops", term: "Experiment tracking" },
  { sectionId: "mlops", term: "Model registry" },
  { sectionId: "mlops", term: "Drift detection" },
  { sectionId: "mlops", term: "Feature store" },
  { sectionId: "data-science", term: "Feature engineering" },
  { sectionId: "data-science", term: "A/B testing" },
  { sectionId: "observability", term: "Tracing / spans" },
];
