/** Recommended group order for learning AI vocabulary on PyGuide. */
export const AI_TERM_STUDY_ORDER: { id: string; title: string }[] = [
  { id: "big-picture", title: "AI Big Picture" },
  { id: "python-ecosystem", title: "Python AI Ecosystem" },
  { id: "data-terms", title: "Data Terms" },
  { id: "ml-basics", title: "Machine Learning Basics" },
  { id: "supervised", title: "Supervised Learning" },
  { id: "training", title: "Model Training" },
  { id: "evaluation", title: "Evaluation" },
  { id: "deep-learning", title: "Deep Learning" },
  { id: "nlp", title: "NLP" },
  { id: "llm", title: "Transformers & LLMs" },
  { id: "prompt-engineering", title: "Prompt Engineering" },
  { id: "embeddings", title: "Embeddings & Vector Search" },
  { id: "rag", title: "RAG" },
  { id: "agents", title: "AI Agents" },
  { id: "mcp", title: "MCP & Tooling" },
  { id: "fine-tuning", title: "Fine-Tuning LLMs" },
  { id: "inference", title: "Inference & Serving" },
  { id: "safety", title: "AI Safety & Security" },
  { id: "mlops", title: "MLOps" },
];
