/** Curriculum phases for the FastAPI index page. */

export const FASTAPI_LEARNING_PHASES = [
  {
    id: "foundations",
    title: "Foundations",
    description: "What FastAPI is, local setup, and your first JSON API.",
    sectionIds: [
      "introduction-to-fastapi",
      "environment-setup",
      "your-first-api",
    ],
  },
  {
    id: "http-and-data",
    title: "HTTP & request data",
    description: "Methods, parameters, bodies, Pydantic models, responses, and status codes.",
    sectionIds: [
      "http-methods",
      "route-parameters",
      "request-body",
      "pydantic-basics",
      "response-models",
      "status-codes",
      "dependency-injection",
    ],
  },
  {
    id: "validation-and-docs",
    title: "Validation & documentation",
    description: "Errors, advanced validation, route metadata, and Swagger / ReDoc.",
    sectionIds: [
      "validation-error-handling",
      "request-validation-advanced",
      "path-operation-configuration",
      "automatic-documentation",
    ],
  },
  {
    id: "web-features",
    title: "Files, forms, middleware & frontends",
    description: "Async, uploads, CORS, static files, and HTML templates.",
    sectionIds: [
      "async-programming",
      "file-uploads",
      "form-data",
      "headers-cookies",
      "middleware",
      "cors",
      "static-files",
      "templates",
    ],
  },
  {
    id: "databases",
    title: "Databases & CRUD",
    description: "SQLAlchemy, SQLModel, migrations, and full CRUD APIs.",
    sectionIds: [
      "database-basics",
      "sqlalchemy",
      "sqlmodel",
      "alembic-migrations",
      "crud-api-development",
    ],
  },
  {
    id: "auth-security",
    title: "Authentication & security",
    description: "Login, JWT, roles, permissions, and API hardening.",
    sectionIds: ["authentication", "authorization", "security"],
  },
  {
    id: "production-ready",
    title: "Testing, architecture & scale",
    description: "Tests, logging, config, routers, pagination, caching, and background work.",
    sectionIds: [
      "background-tasks",
      "websockets",
      "api-versioning",
      "testing",
      "logging",
      "configuration-management",
      "project-architecture",
      "routers",
      "pagination-filtering",
      "rate-limiting",
      "caching",
      "task-queues",
    ],
  },
  {
    id: "ship-it",
    title: "Deploy & operate",
    description: "Docker, CI/CD, monitoring, performance, and advanced FastAPI.",
    sectionIds: [
      "deployment",
      "docker",
      "ci-cd",
      "monitoring-observability",
      "performance-optimization",
      "microservices",
      "graphql-with-fastapi",
      "advanced-fastapi",
    ],
  },
];
